"""鑫基荟优选池产品名单。"""

XINJIHUI_FUND_LIST = [
    {"code": "160807", "name": "长盛沪深 300 指数 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "021494", "name": "长盛沪深 300 指数 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "519100", "name": "长盛中证 A100 指数", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "502053", "name": "长盛中证全指证券", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "015439", "name": "长盛安逸纯债 E", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "510080", "name": "长盛全债指数增强 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "019202", "name": "长盛全债指数增强 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "019203", "name": "长盛全债指数增强 D", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017137", "name": "长盛盛逸 9 个月持有 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017138", "name": "长盛盛逸 9 个月持有 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "080011", "name": "长盛货币 A", "type": "货币", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005230", "name": "长盛货币 B", "type": "货币", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "019145", "name": "长盛货币 E", "type": "货币", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000424", "name": "长盛添利宝 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000425", "name": "长盛添利宝 B", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "163406", "name": "兴全合润混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010418", "name": "财通景气行业混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016234", "name": "财通景气行业混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "018130", "name": "博时 ESG 量化选股 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "018131", "name": "博时 ESG 量化选股 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "090007", "name": "大成策略回报混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "018225", "name": "大成策略回报混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "012835", "name": "招商景气精选股票 A", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "012836", "name": "招商景气精选股票 C", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "487016", "name": "工银瑞信灵活配置混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "018409", "name": "中欧价值回报混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "018410", "name": "中欧价值回报混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000006", "name": "西部利得量化成长混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "011228", "name": "西部利得量化成长混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000746", "name": "招商行业精选股票", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "001437", "name": "易方达瑞享混合 I", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "001438", "name": "易方达瑞享混合 E", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002009", "name": "中欧瑾通灵活配置混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002010", "name": "中欧瑾通灵活配置混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004206", "name": "华商元亨混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "001878", "name": "嘉实沪港深精选股票", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002871", "name": "华夏智胜价值成长股票 A", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002872", "name": "华夏智胜价值成长股票 C", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "001208", "name": "诺安低碳经济股票 A", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010349", "name": "诺安低碳经济股票 C", "type": "股票型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005443", "name": "国金量化多策略 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017874", "name": "国金量化多策略 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002943", "name": "广发多因子混合", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010385", "name": "华安汇嘉精选混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010386", "name": "华安汇嘉精选混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "003026", "name": "安信新价值混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "003027", "name": "安信新价值混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "217002", "name": "招商安泰平衡混合", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010377", "name": "广发价值核心混合 A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010378", "name": "广发价值核心混合 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005994", "name": "国投瑞银中证 500 量化增强 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007089", "name": "国投瑞银中证 500 量化增强 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007144", "name": "国投瑞银沪深 300 量化增强 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007143", "name": "国投瑞银沪深 300 量化增强 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016936", "name": "博时中证 1000 指数增强 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016937", "name": "博时中证 1000 指数增强 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014345", "name": "鹏华中证 500 指数增强 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "588220", "name": "科创 100ETF 基金", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "511880", "name": "银华日利 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159628", "name": "国证 2000ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515220", "name": "煤炭 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "517090", "name": "央企共赢 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "512670", "name": "国防 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159813", "name": "半导体 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159870", "name": "化工 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159673", "name": "沪深 300ETF 鹏华", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159338", "name": "中证 A500ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "563800", "name": "中证 A500ETF 龙头", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "516010", "name": "游戏 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159399", "name": "现金流 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "512400", "name": "有色金属 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159980", "name": "有色 ETF 大成", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515880", "name": "通信 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159865", "name": "养殖 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159828", "name": "医疗 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "511260", "name": "十年国债 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "518800", "name": "黄金基金 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "560050", "name": "MSCI 中国 A50ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515450", "name": "红利低波 50ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "510980", "name": "上证综合 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159739", "name": "大数据 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159993", "name": "证券 ETF 龙头", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159805", "name": "传媒 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159863", "name": "光伏 ETF 基金", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513700", "name": "香港医药 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159581", "name": "红利 ETF 基金", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513400", "name": "道琼斯 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159647", "name": "中药 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "588460", "name": "科创 50 增强 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515800", "name": "800ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513980", "name": "港股科技 50ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159682", "name": "创业 50ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "510500", "name": "中证 500ETF 南方", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "511030", "name": "公司债 ETF 平安", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "511380", "name": "可转债 ETF 博时", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "512040", "name": "价值 100ETF 富国", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "512100", "name": "中证 1000ETF 南方", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513050", "name": "中概互联网 ETF 易方达", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513500", "name": "标普 500ETF 博时", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "561380", "name": "电网设备 ETF 国泰", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159659", "name": "纳斯达克 100ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "561300", "name": "300 增强 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "513170", "name": "恒生央企 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159816", "name": "0-4 地债 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159972", "name": "5 年地债 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "164824", "name": "印度基金 LOF", "type": "QDII", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515330", "name": "300ETF 天弘", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159977", "name": "创业板 ETF 天弘", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159736", "name": "饮食 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515290", "name": "银行 ETF 天弘", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159549", "name": "红利低波动 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159859", "name": "生物医药 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159820", "name": "中证 500ETF 天弘", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159857", "name": "光伏 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159998", "name": "计算机 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159603", "name": "双创龙头 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159997", "name": "电子 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159755", "name": "电池 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159770", "name": "机器人 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159595", "name": "中证 A50ETF 基金", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "515250", "name": "智能汽车 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159792", "name": "港股通互联网 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "511520", "name": "政金债券 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "159650", "name": "国开 ETF", "type": "指数型", "tags": ["鑫基荟", "场内"], "is_xinjihui": True},
    {"code": "006487", "name": "广发中证 1000 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005733", "name": "华夏上证 50ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "011613", "name": "华夏科创板 50ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004343", "name": "南方创业板 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007473", "name": "华夏创业板低波价值联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002611", "name": "博时黄金 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016057", "name": "博时纳斯达克 100 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014519", "name": "博时恒生高股息 ETF 发起式联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014520", "name": "博时恒生高股息 ETF 发起式联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "022424", "name": "广发中证 A500ETF 联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "022425", "name": "广发中证 A500ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017837", "name": "博时中债 7-10 政金债指数 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017838", "name": "博时中债 7-10 政金债指数 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "006733", "name": "博时创业板 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017518", "name": "招商北证 50 成份 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "006075", "name": "博时标普 500ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "015558", "name": "万家中证红利 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "022459", "name": "易方达中证 A500ETF 联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "022460", "name": "易方达中证 A500ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009051", "name": "易方达中证红利 ETF 联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009052", "name": "易方达中证红利 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "110026", "name": "易方达创业板 ETF 联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004744", "name": "易方达创业板 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "011608", "name": "易方达上证科创 50ETF 联接 A", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "011609", "name": "易方达上证科创 50ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016668", "name": "景顺长城全球半导体芯片产业 C", "type": "QDII", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007361", "name": "易方达中短期美元债 C 人民币", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002400", "name": "南方亚洲美元收益债券(QDII)A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002401", "name": "南方亚洲美元债 C 人民币", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014439", "name": "博时恒生科技 ETF 联接 C", "type": "指数型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "008764", "name": "天弘越南市场 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "161226", "name": "国投瑞银白银期货(LOF)A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "019005", "name": "国投瑞银白银期货(LOF)C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "010281", "name": "华夏保守养老一年持有混合(FOF)A", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005725", "name": "国投瑞银恒泽中短债 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "006553", "name": "国投瑞银恒泽中短债 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "110017", "name": "易方达增强回报债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "110018", "name": "易方达增强回报债券 B", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002065", "name": "景顺长城景盛双息收益债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002066", "name": "景顺长城景盛双息收益债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "100018", "name": "富国天利增长债券 A/B", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "017534", "name": "富国天利增长债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "003613", "name": "南方卓元债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014846", "name": "博时恒乐债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "014847", "name": "博时恒乐债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009021", "name": "鹏华丰诚债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009022", "name": "鹏华丰诚债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000171", "name": "易方达裕丰回报债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "016479", "name": "易方达裕丰回报债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000045", "name": "工银产业债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000046", "name": "工银产业债券 B", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "003612", "name": "南方卓元债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "675111", "name": "西部利得汇享债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "675113", "name": "西部利得汇享债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "270048", "name": "广发纯债债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "270049", "name": "广发纯债债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "202108", "name": "南方润元纯债债券 A/B", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "202110", "name": "南方润元纯债债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "002549", "name": "嘉实稳祥纯债债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "003357", "name": "嘉实稳祥纯债债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004042", "name": "华夏鼎茂债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004043", "name": "华夏鼎茂债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "040023", "name": "华安可转债 B", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009272", "name": "博时信用优选债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "009271", "name": "博时信用优选债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "380009", "name": "中银添利债券发起 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005852", "name": "中银稳健添利 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "750003", "name": "安信目标收益 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004706", "name": "南方祥元 C", "type": "混合型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005754", "name": "平安短债 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005755", "name": "平安短债 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000032", "name": "易方达信用债债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000033", "name": "易方达信用债债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "005350", "name": "诺德短债 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007920", "name": "诺德短债 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004451", "name": "汇添富双鑫添利债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "004452", "name": "汇添富双鑫添利债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000130", "name": "大成景兴信用债债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "000131", "name": "大成景兴信用债债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "675100", "name": "西部利得得尊债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007969", "name": "西部利得得尊债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "007562", "name": "景顺长城景泰纯利债券 A", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
    {"code": "013380", "name": "景顺长城景泰纯利债券 C", "type": "债券型", "tags": ["鑫基荟"], "is_xinjihui": True},
]

# Backward-compatible alias for existing service code.
GUOYUAN_FUND_LIST = XINJIHUI_FUND_LIST

FUND_CATEGORIES = {
    "行业": ["消费", "医药", "科技", "新能源", "金融", "制造"],
    "概念": ["鑫基荟", "场内", "蓝筹", "成长", "价值", "红利", "QDII", "量化", "指数", "中小盘", "全球"],
}

FUND_TYPES = ["全部", "股票型", "混合型", "债券型", "指数型", "QDII", "FOF", "货币"]

SORT_FIELDS = {
    "近1月": "near_1m",
    "近3月": "near_3m",
    "近6月": "near_6m",
    "近1年": "near_1y",
    "近3年": "near_3y",
    "今年来": "ytd",
}
